version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"        # Can be daily, weekly, or monthly
      day: "sunday"             # Optional - runs every Sunday
      time: "00:00"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automated"
